### ISSUE TITLE
opening saved input files gives error

### ISSUE THREAD

**Issue by rraman64** [psszabo/SDTrimSP-GUI#2]
Hai,
it is very nice interface.

Gui works fine when input is created from scratch
but fails to load layer.inp when loading saved inp 
though GUI did not crash, layer data is missing and I have to recreate layers

my system config
windows11
WSL-Ubuntu-22.04
Python 3.10.4

error msg
------------------
Traceback (most recent call last):
  File "/home/raja/SDTrimSP-GUI/ui_main.py", line 643, in <lambda>
    self.openAction.triggered.connect(lambda: self.loadFiles())
  File "/home/raja/SDTrimSP-GUI/MainWindow.py", line 1192, in loadFiles
    self.beamComp.addRows(beamEntries)
  File "/home/raja/SDTrimSP-GUI/TableWidgets/BeamCompTable.py", line 93, in addRows
    row.setRowData(e.element, e.abundance, e.kinEnergy, e.angle, e.maxConcentration,\
  File "/home/raja/SDTrimSP-GUI/TableWidgets/BeamCompTable.py", line 54, in setRowData
    super().setRowData(element, maxConcentration, atomicDensity, surfBindEnergy, displEnergy, inelLossModel)
  File "/home/raja/SDTrimSP-GUI/TableWidgets/CompTable.py", line 126, in setRowData
    self.inelLossModel.setCurrentIndex(inelLossModel)
TypeError: setCurrentIndex(self, int): argument 1 has unexpected type 'float'

**Comment by psszabo** [comment]
Hi Rajaraman, 
thank you very much for the interest!

My first guess might be that this is related to python 3.10 that you're running? Do you have a version of 3.9 to try if it works there? In the meantime, I'll try to reproduce your error and work on a fix.

**Comment by rraman64** [comment]
thanks for looking at my issue
I do have ubuntu 20.04 with default python 3.8
GUI works fine
I just installed python 3.9 and created virtual environment to test.
GUI works fine with python 3.9 also.
As you said it may be python 3.10 which came along with ubuntu 22.04
I will switch to 3.9 for the time being

**Comment by psszabo** [comment]
This should be fixed now and the GUI should run under python 3.10 and 3.11 as well.

**Comment by rraman64** [comment]
Thank you. 
it is working fine now with Python 3.10.6
